# Generated by Django 4.2.7 on 2024-05-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Рейтинг игры'),
        ),
    ]
